Save-load function added to the game
cagdasgerede/tetris-1 pull request #11
Opened 2020-12-13 13:50 UTC by cydiann

2020-12-16 08:02 UTC, cagdasgerede commented on src/main/java/spypunk/tetris/model/TetrisInstance.java
> +//import java.util.Optional;
Niye commented out?

2020-12-16 08:10 UTC, cagdasgerede commented on src/main/java/spypunk/tetris/service/TetrisServiceImpl.java
> +//import java.util.Optional;
ditto

2020-12-16 08:11 UTC, cagdasgerede commented on src/main/java/spypunk/tetris/ui/controller/command/cache/TetrisControllerCommandCacheImpl.java
> +    private TetrisControllerCommand createSaveGameCommand() {
Bunlari farkli bir class a al.

2020-12-16 08:11 UTC, cagdasgerede commented on src/main/java/spypunk/tetris/ui/controller/command/cache/TetrisControllerCommandCacheImpl.java
> +    private TetrisControllerCommand createLoadGameCommand() {
ditto

2020-12-16 08:11 UTC, cagdasgerede commented on src/main/java/spypunk/tetris/ui/controller/command/cache/TetrisControllerCommandCacheImpl.java
> +                ex.printStackTrace();
Bu tür hataları Log dosyasına logla.

2020-12-16 08:11 UTC, cagdasgerede commented on src/main/java/spypunk/tetris/ui/controller/command/cache/TetrisControllerCommandCacheImpl.java
> +                ex.printStackTrace();
Log dosyasına gitmeli

2020-12-16 08:18 UTC, cagdasgerede requested changes
Koda biraktığım notlara göre kodunu güncelle.

Arada bir otomatik olarak save etme özelliği ekle. Load ekranında autosave oyunlar ve manual save oyunlar listelensin ve autosave in tarihi de görünsün. Böylece isteyen autosavei de load edebilir, manul savei de load edebilir.

Load ekranında sanırım yalnızca bir dosya load etme dialog penceresi kullanmışsın. Daha custom bir arayüz de eklemelisin. Hangi tarihte hangi levelde hangi puandayken save edilmiş bu bilgilerin de listelenmesi lazım o pencerede. Böylece load ederken kullanıcı load etmeye çalıştığı şeyin ne olduğunu kolayca görür.

Şu ana kadar yaptığın özellikleri gösteren bir videonun linkini PR threadinde paylaş.

2020-12-23 18:33 UTC, cydiann commented
https://user-images.githubusercontent.com/32129122/103027110-4dd94f00-4566-11eb-9ac4-d7fc57f060b0.mp4

Yaptigim degisiklikleri anlattigim video

2020-12-24 08:12 UTC, cydiann commented
Autosave ve load ekranini customize etme ozelliklerini zamanimi etkin kullanamadigim icin projeye ekleyemedim hocam. Eger gec gonderim gibi bir sansim varsa ve o sekilde ekleyebilirsem cok yardimci olur. Eger bugunden sonra degisiklik ekleyemiyorsak istediginiz yeni degisikliklerin bir kismini yetistirememis olarak teslim etmem gerekecek.

2021-03-22 23:57 UTC, closed without merging